/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PanelIndexRouteImport } from './routes/panel/index'
import { Route as PanelKanallarRouteImport } from './routes/panel/kanallar'
import { Route as PanelMesajlarRouteImport } from './routes/panel/mesajlar'
import { Route as PanelModerasyonRouteImport } from './routes/panel/moderasyon'
import { Route as PanelRollerRouteImport } from './routes/panel/roller'
import { Route as PanelUyelerRouteImport } from './routes/panel/uyeler'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelKanallarRoute = PanelKanallarRouteImport.update({
  id: '/kanallar',
  path: '/kanallar',
  getParentRoute: () => PanelRoute,
} as any)
const PanelMesajlarRoute = PanelMesajlarRouteImport.update({
  id: '/mesajlar',
  path: '/mesajlar',
  getParentRoute: () => PanelRoute,
} as any)
const PanelModerasyonRoute = PanelModerasyonRouteImport.update({
  id: '/moderasyon',
  path: '/moderasyon',
  getParentRoute: () => PanelRoute,
} as any)
const PanelRollerRoute = PanelRollerRouteImport.update({
  id: '/roller',
  path: '/roller',
  getParentRoute: () => PanelRoute,
} as any)
const PanelUyelerRoute = PanelUyelerRouteImport.update({
  id: '/uyeler',
  path: '/uyeler',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/kanallar': typeof PanelKanallarRoute
  '/panel/mesajlar': typeof PanelMesajlarRoute
  '/panel/moderasyon': typeof PanelModerasyonRoute
  '/panel/roller': typeof PanelRollerRoute
  '/panel/uyeler': typeof PanelUyelerRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel/kanallar': typeof PanelKanallarRoute
  '/panel/mesajlar': typeof PanelMesajlarRoute
  '/panel/moderasyon': typeof PanelModerasyonRoute
  '/panel/roller': typeof PanelRollerRoute
  '/panel/uyeler': typeof PanelUyelerRoute
  '/panel': typeof PanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/kanallar': typeof PanelKanallarRoute
  '/panel/mesajlar': typeof PanelMesajlarRoute
  '/panel/moderasyon': typeof PanelModerasyonRoute
  '/panel/roller': typeof PanelRollerRoute
  '/panel/uyeler': typeof PanelUyelerRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel'
    | '/panel/kanallar'
    | '/panel/mesajlar'
    | '/panel/moderasyon'
    | '/panel/roller'
    | '/panel/uyeler'
    | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/panel/kanallar'
    | '/panel/mesajlar'
    | '/panel/moderasyon'
    | '/panel/roller'
    | '/panel/uyeler'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/panel'
    | '/panel/kanallar'
    | '/panel/mesajlar'
    | '/panel/moderasyon'
    | '/panel/roller'
    | '/panel/uyeler'
    | '/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRoute: typeof PanelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/kanallar': {
      id: '/panel/kanallar'
      path: '/kanallar'
      fullPath: '/panel/kanallar'
      preLoaderRoute: typeof PanelKanallarRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/mesajlar': {
      id: '/panel/mesajlar'
      path: '/mesajlar'
      fullPath: '/panel/mesajlar'
      preLoaderRoute: typeof PanelMesajlarRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/moderasyon': {
      id: '/panel/moderasyon'
      path: '/moderasyon'
      fullPath: '/panel/moderasyon'
      preLoaderRoute: typeof PanelModerasyonRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/roller': {
      id: '/panel/roller'
      path: '/roller'
      fullPath: '/panel/roller'
      preLoaderRoute: typeof PanelRollerRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/uyeler': {
      id: '/panel/uyeler'
      path: '/uyeler'
      fullPath: '/panel/uyeler'
      preLoaderRoute: typeof PanelUyelerRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelKanallarRoute: typeof PanelKanallarRoute
  PanelMesajlarRoute: typeof PanelMesajlarRoute
  PanelModerasyonRoute: typeof PanelModerasyonRoute
  PanelRollerRoute: typeof PanelRollerRoute
  PanelUyelerRoute: typeof PanelUyelerRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelKanallarRoute: PanelKanallarRoute,
  PanelMesajlarRoute: PanelMesajlarRoute,
  PanelModerasyonRoute: PanelModerasyonRoute,
  PanelRollerRoute: PanelRollerRoute,
  PanelUyelerRoute: PanelUyelerRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRoute: PanelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
