/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PanelIndexRouteImport } from './routes/panel/index'
import { Route as PanelAnalizRouteImport } from './routes/panel/analiz'
import { Route as PanelBotRouteImport } from './routes/panel/bot'
import { Route as PanelEmbedRouteImport } from './routes/panel/embed'
import { Route as PanelKanallarRouteImport } from './routes/panel/kanallar'
import { Route as PanelKorumaRouteImport } from './routes/panel/koruma'
import { Route as PanelMesajlarRouteImport } from './routes/panel/mesajlar'
import { Route as PanelModerasyonRouteImport } from './routes/panel/moderasyon'
import { Route as PanelOtomasyonRouteImport } from './routes/panel/otomasyon'
import { Route as PanelRollerRouteImport } from './routes/panel/roller'
import { Route as PanelSunucuRouteImport } from './routes/panel/sunucu'
import { Route as PanelUyelerRouteImport } from './routes/panel/uyeler'
import { Route as PanelYedeklerRouteImport } from './routes/panel/yedekler'
import { Route as PanelYonetimRouteImport } from './routes/panel/yonetim'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAnalizRoute = PanelAnalizRouteImport.update({
  id: '/analiz',
  path: '/analiz',
  getParentRoute: () => PanelRoute,
} as any)
const PanelBotRoute = PanelBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => PanelRoute,
} as any)
const PanelEmbedRoute = PanelEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => PanelRoute,
} as any)
const PanelKanallarRoute = PanelKanallarRouteImport.update({
  id: '/kanallar',
  path: '/kanallar',
  getParentRoute: () => PanelRoute,
} as any)
const PanelKorumaRoute = PanelKorumaRouteImport.update({
  id: '/koruma',
  path: '/koruma',
  getParentRoute: () => PanelRoute,
} as any)
const PanelMesajlarRoute = PanelMesajlarRouteImport.update({
  id: '/mesajlar',
  path: '/mesajlar',
  getParentRoute: () => PanelRoute,
} as any)
const PanelModerasyonRoute = PanelModerasyonRouteImport.update({
  id: '/moderasyon',
  path: '/moderasyon',
  getParentRoute: () => PanelRoute,
} as any)
const PanelOtomasyonRoute = PanelOtomasyonRouteImport.update({
  id: '/otomasyon',
  path: '/otomasyon',
  getParentRoute: () => PanelRoute,
} as any)
const PanelRollerRoute = PanelRollerRouteImport.update({
  id: '/roller',
  path: '/roller',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSunucuRoute = PanelSunucuRouteImport.update({
  id: '/sunucu',
  path: '/sunucu',
  getParentRoute: () => PanelRoute,
} as any)
const PanelUyelerRoute = PanelUyelerRouteImport.update({
  id: '/uyeler',
  path: '/uyeler',
  getParentRoute: () => PanelRoute,
} as any)
const PanelYedeklerRoute = PanelYedeklerRouteImport.update({
  id: '/yedekler',
  path: '/yedekler',
  getParentRoute: () => PanelRoute,
} as any)
const PanelYonetimRoute = PanelYonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/analiz': typeof PanelAnalizRoute
  '/panel/bot': typeof PanelBotRoute
  '/panel/embed': typeof PanelEmbedRoute
  '/panel/kanallar': typeof PanelKanallarRoute
  '/panel/koruma': typeof PanelKorumaRoute
  '/panel/mesajlar': typeof PanelMesajlarRoute
  '/panel/moderasyon': typeof PanelModerasyonRoute
  '/panel/otomasyon': typeof PanelOtomasyonRoute
  '/panel/roller': typeof PanelRollerRoute
  '/panel/sunucu': typeof PanelSunucuRoute
  '/panel/uyeler': typeof PanelUyelerRoute
  '/panel/yedekler': typeof PanelYedeklerRoute
  '/panel/yonetim': typeof PanelYonetimRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel/analiz': typeof PanelAnalizRoute
  '/panel/bot': typeof PanelBotRoute
  '/panel/embed': typeof PanelEmbedRoute
  '/panel/kanallar': typeof PanelKanallarRoute
  '/panel/koruma': typeof PanelKorumaRoute
  '/panel/mesajlar': typeof PanelMesajlarRoute
  '/panel/moderasyon': typeof PanelModerasyonRoute
  '/panel/otomasyon': typeof PanelOtomasyonRoute
  '/panel/roller': typeof PanelRollerRoute
  '/panel/sunucu': typeof PanelSunucuRoute
  '/panel/uyeler': typeof PanelUyelerRoute
  '/panel/yedekler': typeof PanelYedeklerRoute
  '/panel/yonetim': typeof PanelYonetimRoute
  '/panel': typeof PanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/analiz': typeof PanelAnalizRoute
  '/panel/bot': typeof PanelBotRoute
  '/panel/embed': typeof PanelEmbedRoute
  '/panel/kanallar': typeof PanelKanallarRoute
  '/panel/koruma': typeof PanelKorumaRoute
  '/panel/mesajlar': typeof PanelMesajlarRoute
  '/panel/moderasyon': typeof PanelModerasyonRoute
  '/panel/otomasyon': typeof PanelOtomasyonRoute
  '/panel/roller': typeof PanelRollerRoute
  '/panel/sunucu': typeof PanelSunucuRoute
  '/panel/uyeler': typeof PanelUyelerRoute
  '/panel/yedekler': typeof PanelYedeklerRoute
  '/panel/yonetim': typeof PanelYonetimRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel'
    | '/panel/analiz'
    | '/panel/bot'
    | '/panel/embed'
    | '/panel/kanallar'
    | '/panel/koruma'
    | '/panel/mesajlar'
    | '/panel/moderasyon'
    | '/panel/otomasyon'
    | '/panel/roller'
    | '/panel/sunucu'
    | '/panel/uyeler'
    | '/panel/yedekler'
    | '/panel/yonetim'
    | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/panel/analiz'
    | '/panel/bot'
    | '/panel/embed'
    | '/panel/kanallar'
    | '/panel/koruma'
    | '/panel/mesajlar'
    | '/panel/moderasyon'
    | '/panel/otomasyon'
    | '/panel/roller'
    | '/panel/sunucu'
    | '/panel/uyeler'
    | '/panel/yedekler'
    | '/panel/yonetim'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/panel'
    | '/panel/analiz'
    | '/panel/bot'
    | '/panel/embed'
    | '/panel/kanallar'
    | '/panel/koruma'
    | '/panel/mesajlar'
    | '/panel/moderasyon'
    | '/panel/otomasyon'
    | '/panel/roller'
    | '/panel/sunucu'
    | '/panel/uyeler'
    | '/panel/yedekler'
    | '/panel/yonetim'
    | '/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRoute: typeof PanelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/analiz': {
      id: '/panel/analiz'
      path: '/analiz'
      fullPath: '/panel/analiz'
      preLoaderRoute: typeof PanelAnalizRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/bot': {
      id: '/panel/bot'
      path: '/bot'
      fullPath: '/panel/bot'
      preLoaderRoute: typeof PanelBotRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/embed': {
      id: '/panel/embed'
      path: '/embed'
      fullPath: '/panel/embed'
      preLoaderRoute: typeof PanelEmbedRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/kanallar': {
      id: '/panel/kanallar'
      path: '/kanallar'
      fullPath: '/panel/kanallar'
      preLoaderRoute: typeof PanelKanallarRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/koruma': {
      id: '/panel/koruma'
      path: '/koruma'
      fullPath: '/panel/koruma'
      preLoaderRoute: typeof PanelKorumaRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/mesajlar': {
      id: '/panel/mesajlar'
      path: '/mesajlar'
      fullPath: '/panel/mesajlar'
      preLoaderRoute: typeof PanelMesajlarRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/moderasyon': {
      id: '/panel/moderasyon'
      path: '/moderasyon'
      fullPath: '/panel/moderasyon'
      preLoaderRoute: typeof PanelModerasyonRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/otomasyon': {
      id: '/panel/otomasyon'
      path: '/otomasyon'
      fullPath: '/panel/otomasyon'
      preLoaderRoute: typeof PanelOtomasyonRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/roller': {
      id: '/panel/roller'
      path: '/roller'
      fullPath: '/panel/roller'
      preLoaderRoute: typeof PanelRollerRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/sunucu': {
      id: '/panel/sunucu'
      path: '/sunucu'
      fullPath: '/panel/sunucu'
      preLoaderRoute: typeof PanelSunucuRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/uyeler': {
      id: '/panel/uyeler'
      path: '/uyeler'
      fullPath: '/panel/uyeler'
      preLoaderRoute: typeof PanelUyelerRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/yedekler': {
      id: '/panel/yedekler'
      path: '/yedekler'
      fullPath: '/panel/yedekler'
      preLoaderRoute: typeof PanelYedeklerRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/yonetim': {
      id: '/panel/yonetim'
      path: '/yonetim'
      fullPath: '/panel/yonetim'
      preLoaderRoute: typeof PanelYonetimRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelAnalizRoute: typeof PanelAnalizRoute
  PanelBotRoute: typeof PanelBotRoute
  PanelEmbedRoute: typeof PanelEmbedRoute
  PanelKanallarRoute: typeof PanelKanallarRoute
  PanelKorumaRoute: typeof PanelKorumaRoute
  PanelMesajlarRoute: typeof PanelMesajlarRoute
  PanelModerasyonRoute: typeof PanelModerasyonRoute
  PanelOtomasyonRoute: typeof PanelOtomasyonRoute
  PanelRollerRoute: typeof PanelRollerRoute
  PanelSunucuRoute: typeof PanelSunucuRoute
  PanelUyelerRoute: typeof PanelUyelerRoute
  PanelYedeklerRoute: typeof PanelYedeklerRoute
  PanelYonetimRoute: typeof PanelYonetimRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelAnalizRoute: PanelAnalizRoute,
  PanelBotRoute: PanelBotRoute,
  PanelEmbedRoute: PanelEmbedRoute,
  PanelKanallarRoute: PanelKanallarRoute,
  PanelKorumaRoute: PanelKorumaRoute,
  PanelMesajlarRoute: PanelMesajlarRoute,
  PanelModerasyonRoute: PanelModerasyonRoute,
  PanelOtomasyonRoute: PanelOtomasyonRoute,
  PanelRollerRoute: PanelRollerRoute,
  PanelSunucuRoute: PanelSunucuRoute,
  PanelUyelerRoute: PanelUyelerRoute,
  PanelYedeklerRoute: PanelYedeklerRoute,
  PanelYonetimRoute: PanelYonetimRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRoute: PanelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
